In [1]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [2]:
train = pd.read_csv('train.csv')
X= (train.iloc[:,1:].values).astype('float32') # all pixel values
y = train.iloc[:,0].values.astype('int32') # only labels i.e targets digits
X = X.reshape(X.shape[0], 28, 28,1)
print(X.shape)

(42000, 28, 28, 1)


In [7]:
mean = X.mean().astype(np.float32)
std = X.std().astype(np.float32)

def standardize (X):
    return  (X - mean) / std

standardize(X).mean()
standardize(X).std()
X = X.reshape(X.shape[0], 784)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
print(X_train.shape)

(29400, 784)


In [9]:
xgboosting= XGBClassifier()
xgboosting.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [10]:
predictions = xgboosting.predict(X_test)
print(classification_report(y_test,predictions))
print('\n')
print(confusion_matrix(y_test,predictions))

             precision    recall  f1-score   support

          0       0.97      0.98      0.97      1200
          1       0.96      0.98      0.97      1389
          2       0.93      0.93      0.93      1294
          3       0.92      0.88      0.90      1355
          4       0.91      0.93      0.92      1222
          5       0.92      0.89      0.91      1085
          6       0.94      0.95      0.94      1256
          7       0.94      0.92      0.93      1359
          8       0.91      0.92      0.92      1209
          9       0.88      0.90      0.89      1231

avg / total       0.93      0.93      0.93     12600



[[1173    0    2    2    4    4    6    0    7    2]
 [   1 1368    7    3    1    1    4    1    3    0]
 [   7    6 1197   15   17    0   13   21   15    3]
 [   5   10   29 1197    1   37    8   17   27   24]
 [   1    3    4    0 1142    2    9    5    7   49]
 [   7    7    3   40   10  969   24    4   16    5]
 [  10    3    3    0   12   21 1191    1

C:\Users\ymk13\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
