In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [2]:
train = pd.read_csv('train.csv')
#test = pd.read_csv('test.csv')

In [3]:
X = train.drop('label',axis=1)
y = train['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [4]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
predictions = dtree.predict(X_test)
print(classification_report(y_test,predictions))
print('\n')
print(confusion_matrix(y_test,predictions))

             precision    recall  f1-score   support

          0       0.91      0.91      0.91      1200
          1       0.92      0.95      0.93      1389
          2       0.85      0.82      0.83      1294
          3       0.78      0.79      0.79      1355
          4       0.83      0.85      0.84      1222
          5       0.78      0.78      0.78      1085
          6       0.89      0.88      0.88      1256
          7       0.89      0.89      0.89      1359
          8       0.77      0.78      0.78      1209
          9       0.84      0.82      0.83      1231

avg / total       0.85      0.85      0.85     12600



[[1088    5   16   12   10   17   20   10   17    5]
 [   0 1316   13   15    7    5    7    1   18    7]
 [  21   25 1058   45   18   13   19   33   47   15]
 [  12   20   38 1069   10   80    6   27   55   38]
 [   6   11   14   26 1041   13   20   13   27   51]
 [  16    9   21   69   21  847   34   12   36   20]
 [  18    4   17   14   34   34 1099    5

In [6]:
rfc = RandomForestClassifier(n_estimators=600)
rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)
print(classification_report(y_test,rfc_pred))
print('\n')
print(confusion_matrix(y_test,rfc_pred))

             precision    recall  f1-score   support

          0       0.98      0.99      0.98      1200
          1       0.98      0.99      0.99      1389
          2       0.96      0.96      0.96      1294
          3       0.96      0.94      0.95      1355
          4       0.97      0.97      0.97      1222
          5       0.97      0.96      0.96      1085
          6       0.97      0.98      0.97      1256
          7       0.97      0.96      0.96      1359
          8       0.95      0.95      0.95      1209
          9       0.93      0.94      0.94      1231

avg / total       0.96      0.96      0.96     12600



[[1185    0    2    0    2    1    5    0    5    0]
 [   0 1374    6    3    1    1    2    1    0    1]
 [   5    3 1248    5    9    0    6   10    8    0]
 [   3    1   13 1270    1   19    2   18   17   11]
 [   2    0    1    0 1182    0    8    2    4   23]
 [   1    2    2   13    1 1039   11    1    7    8]
 [   7    2    1    0    4    4 1231    0